data:
  data_folder: "./datasets/ICEWS14s"
  hist_len: 3
  bidirectional: true
  prepend_val_and_test: true
  shuffle_seed: 1234

model:
  _class: tkgl.models.cenet.CENet
  hidden_size: 200
  rgcn_num_layers: 2
  rgcn_num_heads: 4
  rgcn_self_loop: true
  rgcn_message_op: uev
  rgcn_attention_op: m
  convtranse_kernel_size: 3
  convtranse_channels: 50
  dropout: 0.2
  evolve_rel: true

training:
  criterion:
    # _class: tkgl.models.cen.HistEntLoss
    _class: tkgl.models.EntLoss
  optim:
    _class: torch.optim.Adam
    lr: 1.0e-3
    weight_decay: 1.0e-5
  patient: 5
  grad_clip_norm: 1.0
